[package]
name = "sparkle"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { version = "0.1.0", path = "../common" }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
